# 1. Setup: Install Python 3.11 dan Library C++ untuk GeoPandas (GDAL)
[phases.setup]
nixPkgs = ["python311", "gdal", "geos", "gcc", "bash"]

# 2. Install: Langsung pip install (Nixpacks otomatis handle path-nya)
[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

# 3. Start: Jalankan server langsung (Tanpa activate venv manual)
[phases.start]
cmds = ["python -m uvicorn server:app --host 0.0.0.0 --port $PORT"]