[phases.setup]
# Setup Python 3.11 dan library GDAL (Wajib untuk GeoPandas)
nixPkgs = ["python311", "gdal", "geos", "gcc"]

[phases.install]
# 1. Buat venv
# 2. Install requirements KE DALAM venv tersebut (pakai .venv/bin/pip)
cmds = [
    "python -m venv .venv",
    ".venv/bin/pip install -r requirements.txt"
]

[phases.start]
# JANGAN pakai 'source activate'. Panggil python dari venv langsung.
# Ini jauh lebih aman dan anti-error.
cmds = [".venv/bin/python -m uvicorn server:app --host 0.0.0.0 --port $PORT"]